services:
  - type: web
    name: yohannes-kefale-portfolio
    runtime: node
    plan: free
    buildCommand: npm run setup && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
